name: 'Terraform'

on: 
  push:
    branches:
      - DEV
      - UAT
  workflow_dispatch:
    inputs:
      environment:
        description: "Provide environment to the Pipeline"
        type: choice
        options:
          - dev
          - uat
          - prod
        default: Dev
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    continue-on-error: true
    name: 'Terraform'
    runs-on: ${{ matrix.os }}
    environment: ${{inputs.environment}}
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        shell: bash
    steps:
    # Checkout the repository to the GitHub Actions runner
      - name: code checkout
        uses: actions/checkout@v5

    #Connect AWS account with OIDC Provider
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::805702559038:role/Github_Actions_EKS_Repo
      
    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init

    # # Checks that all Terraform configuration files adhere to a canonical format
    #   - name: Terraform Format
    #     run: terraform fmt -check

    # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan

    # Execution of Terraform apply
      - name: Terraform apply
        run: terraform destroy --auto-approve

